services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cek-lab
    ports:
      - "8001:80"
    volumes:
      - .:/app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: cek-lab-mysql
      DB_PORT: 3306
      DB_DATABASE: ceklab
      DB_USERNAME: user_ceklab
      DB_PASSWORD: skandakradev
    command: php artisan serve --host=0.0.0.0 --port=80
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: cek-lab-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: skandakradev
      MYSQL_DATABASE: ceklab
      MYSQL_USER: user_ceklab
      MYSQL_PASSWORD: skandakradev
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
