services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel_net

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel_crud_db
      MYSQL_USER: user_db_crud
      MYSQL_PASSWORD: pass_root
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel_net

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "9001:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
